[project]
name = "gpt-av-crowdsourced"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.21"
dependencies = [
    "deepseek-vl==0.0.1.dev0",
    "langchain==0.3.21",
    "numpy==1.26.4",
    "openai==1.68.2",
    "pandas==2.2.3",
    "pyyaml==6.0.2",
    "requests==2.32.3",
    "torch==2.1.0",
    "torchvision==0.16.0",
    "tqdm==4.67.1",
    "transformers==4.38.2",
    "xformers==0.0.22.post7",
]

[tool.uv.extra-build-dependencies]
xformers = ["setuptools", "wheel", "ninja", "cmake"]
