import os
import json
import base64
import pandas as pd
import common
from openai import OpenAI  # type: ignore
from langchain.memory import ConversationBufferMemory
from langchain.schema import messages_from_dict, messages_to_dict
from custom_logger import CustomLogger
from logmod import logs

logs(show_level='info', show_color=True)
logger = CustomLogger(__name__)  # use custom logger

data_folder = common.get_configs("data")


class GPT_ImageAnalyser:
    """
    A class to analyse images using the GPT-4 Vision model.

    This class encodes the provided image, sends it to the GPT-4 Vision API along with a prompt,
    processes conversation history, updates a CSV file with the response, and manages conversation memory.
    """

    def __init__(self, image_path, prompt, use_history=True, max_memory_messages=6):
        """
        Initialise the GPT_ImageAnalyser with image, prompt, and conversation history settings.

        Args:
            image_path (str): The path to the image file to be analysed.
            prompt (str): The prompt or instruction to be provided to the model.
            use_history (bool): Flag indicating whether to include conversation history.
            max_memory_messages (int): The maximum number of conversation history messages to store.
        """
        self.image_path = image_path
        self.prompt = prompt
        self.use_history = use_history
        self.max_memory_messages = max_memory_messages
        self.first_run = True  # Indicates whether this is the first analysis run.
        # The output CSV filename is set based on a random seed configuration.
        self.output_csv = os.path.join(data_folder,
                                       f"output_{common.get_configs('random_seed')}.csv")
        self.model_name = "gpt-4o"
        # Initialise the OpenAI client for API calls.
        self.client = OpenAI(api_key=common.get_secrets("OPENAI_API_KEY"))  # type: ignore
        # File path to save conversation memory.
        self.memory_file = os.path.join(data_folder, "chatgpt_memory.json")
        # Initialise conversation memory using LangChain.
        self.memory = ConversationBufferMemory(return_messages=True)
        # Load any existing conversation memory from file.
        self.load_memory()

    def load_memory(self):
        """
        Load conversation memory from a JSON file.

        This method:
        1. Attempts to open and read the memory file specified by `self.memory_file`.
        2. Loads the conversation messages from JSON format.
        3. Converts the loaded data into a list of message objects.
        4. Limits the stored messages to the most recent `self.max_memory_messages`.
        5. If the memory file is not found, it silently skips loading.

        Args:
            None

        Returns:
            None: Updates `self.memory.chat_memory.messages` in place.
        """
        try:
            # Open the memory file and load stored messages
            with open(self.memory_file, "r") as f:
                messages = json.load(f)

                # Convert dictionary representation to message objects
                full_list = messages_from_dict(messages)

                # Keep only the most recent `max_memory_messages`
                self.memory.chat_memory.messages = full_list[-self.max_memory_messages:]
        except FileNotFoundError:
            # If the memory file doesn't exist, skip without raising an error
            pass

    def save_memory(self):
        """
        Save the current conversation memory to a JSON file.

        This method:
        1. Converts the current chat memory into a dictionary format using `messages_to_dict`.
        2. Writes the serialised memory to the file path specified by `self.memory_file`.
        3. Formats the JSON with indentation for readability.

        Args:
            None

        Returns:
            None: Writes memory data to disk; does not return a value.
        """
        # Convert message objects to dictionary format for serialization
        messages = messages_to_dict(self.memory.chat_memory.messages)

        # Write serialised messages to file in JSON format
        with open(self.memory_file, "w") as f:
            json.dump(messages, f, indent=2)

    def analyse_image(self, seed=42):
        """
        Analyse an image using GPT-4 Vision and save the generated response to a CSV file.

        This method:
        1. Encodes the target image as base64.
        2. Builds a prompt that may include prior conversation history.
        3. Sends the prompt and image to the GPT-4 Vision model.
        4. Stores the generated output in an output CSV, creating or updating entries.
        5. Updates the conversation memory if history tracking is enabled.

        Args:
            seed (int, optional): Random seed value used to determine the output CSV filename.
                Defaults to 42.

        Returns:
            str: The text content generated by the GPT-4 Vision API.
        """
        # Determine output CSV file path
        self.output_csv = os.path.join(data_folder, f"output_{seed}.csv")

        # Encode the image file into base64 format
        with open(self.image_path, "rb") as img_file:
            base64_image = base64.b64encode(img_file.read()).decode("utf-8")

        # Build prompt — include history if enabled and this is not the first run
        if self.use_history and not self.first_run:
            formatted_history = ""
            for message in self.memory.chat_memory.messages:
                if message.__class__.__name__ == "HumanMessage":
                    formatted_history += f"History - Human: {message.content}\n"
                elif message.__class__.__name__ == "AIMessage":
                    formatted_history += f"History - AI: {message.content}\n"

            full_prompt = (
                f"{common.get_configs('base_prompt')}\n\n"
                f"{common.get_configs('history_intro')}\n"
                f"{formatted_history}\n"
                f"{common.get_configs('current_image_instruction')}"
            )
        else:
            full_prompt = self.prompt

        # Send request to GPT-4 Vision API
        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": full_prompt},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{base64_image}"
                            },
                        },
                    ],
                }
            ],
            max_tokens=1000,
            temperature=common.get_configs("temperature")
        )

        # Extract generated text from API response
        content = response.choices[0].message.content

        # Update conversation history if enabled
        if self.use_history:
            self.memory.chat_memory.add_user_message(self.prompt)
            self.memory.chat_memory.add_ai_message(content)  # type: ignore
            self.memory.chat_memory.messages = self.memory.chat_memory.messages[-self.max_memory_messages:]
            self.save_memory()

        # Mark this run as no longer the first
        self.first_run = False

        image_name = os.path.basename(self.image_path)

        # Try loading existing CSV or create a new one
        try:
            df = pd.read_csv(self.output_csv)
        except FileNotFoundError:
            df = pd.DataFrame(columns=["image"])

        # Ensure the current model column exists
        if self.model_name not in df.columns:
            df[self.model_name] = pd.NA

        # Update or append the result for this image
        if image_name in df["image"].values:
            df.loc[df["image"] == image_name, self.model_name] = content
        else:
            new_row = {"image": image_name, self.model_name: content}
            df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

        # Save updated CSV
        df.to_csv(self.output_csv, index=False)
        logger.info(f"\nSaved GPT-4 Vision output for {image_name} to {self.output_csv}")

        return content


if __name__ == "__main__":
    # The main block is left empty for now.
    pass
